export type AlphabetItem = {
    alphabet: string
    imgSrc: string
    imgName: string
    imgNameTranslation: string
    audioSrc: string
    alts: string[]
}

export const ALPHABET_ITEMS: AlphabetItem[] = [
    {
        alphabet: 'ئا',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-horse.png`,
        imgName: 'ئات',
        imgNameTranslation: 'Horse',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/1.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/1_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/1_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/1_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/1_4.gif`,
        ],
    },
    {
        alphabet: 'ئە',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-mirror.png`,
        imgName: 'ئەينەك',
        imgNameTranslation: 'Mirror',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/2.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/2_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/2_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/2_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/2_4.gif`,
        ],
    },
    {
        alphabet: 'ب',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-fish.png`,
        imgName: 'بىلىق',
        imgNameTranslation: 'Fish',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/3.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/3_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/3_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/3_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/3_4.gif`,
        ],
    },
    {
        alphabet: 'پ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-boat.png`,
        imgName: 'پاراخوت',
        imgNameTranslation: 'Boat',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/4.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/4_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/4_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/4_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/4_4.gif`,
        ],
    },
    {
        alphabet: 'ت',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-watermelon.png`,
        imgName: 'تاۋۇز',
        imgNameTranslation: 'Watermelon',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/5.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/5_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/5_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/5_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/5_4.gif`,
        ],
    },
    {
        alphabet: 'ج',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-furcoat2.png`,
        imgName: 'جۇۋا',
        imgNameTranslation: 'Fur Coat',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/6.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/6_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/6_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/6_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/6_4.gif`,
        ],
    },
    {
        alphabet: 'چ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-kettle.png`,
        imgName: 'چۆگۈن',
        imgNameTranslation: 'Kettle',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/7.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/7_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/7_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/7_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/7_4.gif`,
        ],
    },
    {
        alphabet: 'خ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-rooster.png`,
        imgName: 'خوراز',
        imgNameTranslation: 'Rooster',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/8.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/8_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/8_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/8_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/8_4.gif`,
        ],
    },
    {
        alphabet: 'د',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-doctor.png`,
        imgName: 'دوكتور',
        imgNameTranslation: 'Doctor',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/9.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/9_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/9_2.gif`,
        ],
    },
    {
        alphabet: 'ر',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-rocket.png`,
        imgName: 'راكېتا',
        imgNameTranslation: 'Rocket',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/10.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/10_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/10_2.gif`,
        ],
    },
    {
        alphabet: 'ز',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-giraffe.png`,
        imgName: 'زىراپە',
        imgNameTranslation: 'Giraffe',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/11.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/11_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/11_2.gif`,
        ],
    },
    {
        alphabet: 'ژ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-journal.png`,
        imgName: 'ژۇرنال',
        imgNameTranslation: 'Journal',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/12.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/12_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/12_2.gif`,
        ],
    },
    {
        alphabet: 'س',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-clock.png`,
        imgName: 'سائەت',
        imgNameTranslation: 'Clock',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/13.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/13_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/13_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/13_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/13_4.gif`,
        ],
    },
    {
        alphabet: 'ش',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-lion2.png`,
        imgName: 'شىر',
        imgNameTranslation: 'Lion',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/14.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/14_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/14_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/14_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/14_4.gif`,
        ],
    },
    {
        alphabet: 'غ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-goose.png`,
        imgName: 'غاز',
        imgNameTranslation: 'Goose',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/15.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/15_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/15_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/15_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/15_4.gif`,
        ],
    },
    {
        alphabet: 'ف',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-fountain.png`,
        imgName: 'فونتان',
        imgNameTranslation: 'Fountain',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/16.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/16_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/16_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/16_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/16_4.gif`,
        ],
    },
    {
        alphabet: 'ق',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-sheep.png`,
        imgName: 'قوي',
        imgNameTranslation: 'Sheep',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/17.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/17_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/17_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/17_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/17_4.gif`,
        ],
    },
    {
        alphabet: 'ك',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-cow.png`,
        imgName: 'كالا',
        imgNameTranslation: 'Cow',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/18.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/18_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/18_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/18_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/18_4.gif`,
        ],
    },
    {
        alphabet: 'گ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-flowers.png`,
        imgName: 'گۇل',
        imgNameTranslation: 'Flowers',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/19.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/19_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/19_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/19_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/19_4.gif`,
        ],
    },
    {
        alphabet: 'ڭ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-tshirt.png`,
        imgName: 'كۆڭلەك',
        imgNameTranslation: 'Shirt',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/20.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/20_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/20_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/20_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/20_4.gif`,
        ],
    },
    {
        alphabet: 'ل',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-kite.png`,
        imgName: 'لەگلەك',
        imgNameTranslation: 'Kite',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/21.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/21_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/21_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/21_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/21_4.gif`,
        ],
    },
    {
        alphabet: 'م',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-monkey.png`,
        imgName: 'مايمۇن',
        imgNameTranslation: 'Monkey',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/22.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/22_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/22_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/22_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/22_4.gif`,
        ],
    },
    {
        alphabet: 'ن',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-naan.png`,
        imgName: 'نان',
        imgNameTranslation: 'Naan',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/23.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/23_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/23_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/23_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/23_4.gif`,
        ],
    },
    {
        alphabet: 'ھ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-bee.png`,
        imgName: 'ھەرە',
        imgNameTranslation: 'Bee',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/24.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/24_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/24_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/24_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/24_4.gif`,
        ],
    },
    {
        alphabet: 'ئو',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-fire.png`,
        imgName: 'ئوت',
        imgNameTranslation: 'Fire',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/25.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/25_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/25_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/25_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/25_4.gif`,
        ],
    },
    {
        alphabet: 'ئۇ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-flour.png`,
        imgName: 'ئۇن',
        imgNameTranslation: 'Flour',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/26.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/26_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/26_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/26_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/26_4.gif`,
        ],
    },
    {
        alphabet: 'ئۆ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-home.png`,
        imgName: 'ئۆي',
        imgNameTranslation: 'House',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/27.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/27_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/27_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/27_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/27_4.gif`,
        ],
    },
    {
        alphabet: 'ئۈ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-grapes.png`,
        imgName: 'ئۈزۈم',
        imgNameTranslation: 'Grapes',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/28.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/28_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/28_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/28_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/28_4.gif`,
        ],
    },
    {
        alphabet: 'ۋ',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-bicycle.png`,
        imgName: 'ۋېلىسىپىت',
        imgNameTranslation: 'Bicycle',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/29.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/29_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/29_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/29_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/29_4.gif`,
        ],
    },
    {
        alphabet: 'ئې',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-bear.png`,
        imgName: 'ئېيىق',
        imgNameTranslation: 'Bear',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/30.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/30_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_4.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_5.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_6.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_7.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/30_8.gif`,
        ],
    },
    {
        alphabet: 'ئى',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-dog.png`,
        imgName: 'ئىت',
        imgNameTranslation: 'Dob',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/31.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/31_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_4.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_5.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_6.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_7.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/31_8.gif`,
        ],
    },
    {
        alphabet: 'ي',
        imgSrc: `${process.env.PUBLIC_URL}/assets/images/illustration-tiger.png`,
        imgName: 'يولۋاس',
        imgNameTranslation: 'Tiger',
        audioSrc: `${process.env.PUBLIC_URL}/assets/audio/32.wav`,
        alts: [
            `${process.env.PUBLIC_URL}/assets/images/alts/32_1.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/32_2.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/32_3.gif`,
            `${process.env.PUBLIC_URL}/assets/images/alts/32_4.gif`,
        ],
    },
]

export const COLOURS = [
    '#f44336',
    '#e91e63',
    '#9c27b0',
    '#673ab7',
    '#3f51b5',
    '#2196f3',
    '#03a9f4',
    '#00bcd4',
    '#009688',
    '#4caf50',
    '#8bc34a',
    '#cddc39',
    '#ffeb3b',
    '#ffc107',
    '#ff9800',
    '#ff5722',
    '#795548',
    '#9e9e9e',
    '#607d8b',
]

export const MAX_GIF_ANIMATIONS = 3
